# Practice Day 1

##### Arrays & the NumPy Foundation
##### Creating arrays, attributes, indexing & slicing
##### Q1 Create a 1D array of numbers 1–20. Slice out only the even-indexed elements.
##### Q2 Create a 3×4 array of zeros, then replace the entire second row with 7s.
##### Q3 Create two arrays using np.linspace() — one from 0 to 1 (10 elements) and one from 0 to 100 (10 elements). Print their dtypes and shapes.
##### Q4 Given the array [3, 1, 4, 1, 5, 9, 2, 6], return all elements greater than 4 using boolean indexing.
##### Q5 Create a 4×4 identity-like array where the diagonal is [1, 2, 3, 4] using np.diag().

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Q1 Create a 1D array of numbers 1–20. Slice out only the even-indexed elements.

In [6]:
arr_q1 = np.arange(1,21,1)
arr_q1[arr_q1%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Q2 Create a 3×4 array of zeros, then replace the entire second row with 7s.

In [16]:
arr_q2 = np.zeros((3,4))
arr_q2[1,:] = 7
arr_q2

array([[0., 0., 0., 0.],
       [7., 7., 7., 7.],
       [0., 0., 0., 0.]])

In [ ]:
# Q3 Create two arrays using np.linspace() — one from 0 to 1 (10 elements) and one from 0 to 100 (10 elements). 
# Print their dtypes and shapes.

In [19]:
arr_q3_1 = np.linspace(0,1,10)
print(arr_q3_1)
print(arr_q3_1.shape)
print(arr_q3_1.dtype)
arr_q3_2 = np.linspace(1,100,10)
print(arr_q3_2)
print(arr_q3_2.shape)
print(arr_q3_2.dtype)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
(10,)
float64
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
(10,)
float64


In [ ]:
# Q4 Given the array [3, 1, 4, 1, 5, 9, 2, 6], return all elements greater than 4 using boolean indexing.

In [20]:
arr_q4 = np.array([3, 1, 4, 1, 5, 9, 2, 6])
arr_q4[arr_q4>4]

array([5, 9, 6])

In [ ]:
# Q5 Create a 4×4 identity-like array where the diagonal is [1, 2, 3, 4] using np.diag().

In [28]:
arr_q5 = np.diag([1,2,3,4])
arr_q5

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])