# Practice Day 2

##### Reshaping, Stacking & Array Manipulation
##### reshape, flatten, vstack, hstack, copy vs view
##### Q1 Create a 1D array of 12 elements and reshape it into 3×4, then 2×6, then 4×3. Print each shape.
##### Q2 Create two 3×3 arrays and stack them vertically with vstack and horizontally with hstack. What are the resulting shapes?
##### Q3 Create a 4×4 array and extract just the top-right 2×2 corner using slicing.
##### Q4 Create array a = np.arange(9).reshape(3,3). Create a view b = a[1:]. Modify b[0, 0] = 99. What happens to a? Now try with .copy() and explain the difference.
##### Q5 Create a 1D array [1, 2, 3] and use np.tile() to repeat it into a 3×3 array.

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Q1 Create a 1D array of 12 elements and reshape it into 3×4, then 2×6, then 4×3. Print each shape.

In [4]:
arr_q1 = np.arange(12)
print(arr_q1.reshape(3,4))
print(arr_q1.reshape(2,6))
print(arr_q1.reshape(4,3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Q2 Create two 3×3 arrays and stack them vertically with vstack and horizontally with hstack. What are the resulting shapes?

In [ ]:
a = np.zeros((3,3))
b = np.ones((3,3))
c1 = np.vstack([a,b])
print(c1)
print(c1.shape)
c2 = np.hstack([a,b])
print(c2)
print(c2.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(6, 3)
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
(3, 6)


: 

In [ ]:
# Q3 Create a 4×4 array and extract just the top-right 2×2 corner using slicing.

In [24]:
arr_q3 = np.arange(16)
arr_q3 = arr_q3.reshape(4,4)
print(arr_q3)
print(arr_q3[:2,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[2 3]
 [6 7]]


In [ ]:
# Q4 Create array a = np.arange(9).reshape(3,3). Create a view b = a[1:]. Modify b[0, 0] = 99. What happens to a? Now try with .copy() and explain the difference.

In [29]:
a = np.arange(9).reshape(3,3)
b = a[1:]
b[0,0]=99
a

array([[ 0,  1,  2],
       [99,  4,  5],
       [ 6,  7,  8]])

In [ ]:
a = np.arange(9).reshape(3,3)
b = a[1:].copy() # this is a copy only so any changes on the copy will not impact the original array
b[0,0]=99 
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Q5 Create a 1D array [1, 2, 3] and use np.tile() to repeat it into a 3×3 array.

In [39]:
arr_q5 = np.arange(1,4,1)
print(np.tile(arr_q5,(3,1)))


[[1 2 3]
 [1 2 3]
 [1 2 3]]
