# Practice Day 4

##### Linear Algebra & Random Numbers
##### np.dot, np.linalg, np.random, reproducibility
##### Q1 Create two 3×3 matrices A and B. Compute their dot product using both np.dot() and @. Verify they give the same result.
##### Q2 Create a 3×3 matrix, compute its determinant and inverse using np.linalg. Verify that A @ inv(A) gives the identity matrix (approximately).
##### Q3 Set np.random.seed(42). Generate 1000 random numbers from a standard normal distribution. Print the mean and std — what do you expect them to be close to?
##### Q4 Simulate rolling a 6-sided die 10,000 times using np.random.choice(). Count how many times each face appeared using np.unique() with return_counts=True.
##### Q5 Generate a 100×5 array of random data representing 100 samples and 5 features. Compute the mean and standard deviation of each feature (column).

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Q1 Create two 3×3 matrices A and B. Compute their dot product using both np.dot() and @. Verify they give the same result.

In [7]:
A = np.random.randint(1,10,size=(3,3))
B = np.random.randint(1,10,size=(3,3))
print(A)
print(B)
print(np.dot(A,B))
print(A@B)
print(np.dot(A,B) == A@B)

[[3 2 5]
 [4 9 5]
 [6 4 4]]
[[8 1 2]
 [3 9 5]
 [1 7 7]]
[[ 35  56  51]
 [ 64 120  88]
 [ 64  70  60]]
[[ 35  56  51]
 [ 64 120  88]
 [ 64  70  60]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Q2 Create a 3×3 matrix, compute its determinant and inverse using np.linalg. Verify that A @ inv(A) gives the identity matrix (approximately).

In [11]:
C = np.random.randint(1,10,size=(3,3))
print(C)
inv_C = np.linalg.inv(C)
print(inv_C)
np.round(C @ inv_C,10)

[[5 1 2]
 [5 7 3]
 [2 1 3]]
[[ 0.28571429 -0.01587302 -0.17460317]
 [-0.14285714  0.17460317 -0.07936508]
 [-0.14285714 -0.04761905  0.47619048]]


array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [ ]:
# Also worth knowing: if the determinant is 0, the matrix has no inverse and np.linalg.inv() will error. 
# Checking it first is good defensive practice.

In [39]:
print('Determinant:', np.linalg.det(C))

Determinant: 62.99999999999999


In [ ]:
# Q3 Set np.random.seed(42). Generate 1000 random numbers from a standard normal distribution. Print the mean and std — what do you expect them to be close to?

In [16]:
np.random.seed(42)
D = np.random.randn(1000)
print('Mean:', np.round(np.mean(D),2))  # Should be close to 0
print('STD:', np.round(np.std(D),2))     # Should be close to 1 

Mean: 0.02
STD: 0.98


In [ ]:
# Q4 Simulate rolling a 6-sided die 10,000 times using np.random.choice(). Count how many times each face appeared using np.unique() with return_counts=True.

In [24]:
E = np.random.choice(np.arange(1,7,1),size=10000,replace=True)
np.unique(E, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([1637, 1621, 1687, 1615, 1795, 1645]))

In [ ]:
# Q5 Generate a 100×5 array of random data representing 100 samples and 5 features. Compute the mean and standard deviation of each feature (column).

In [33]:
F = np.random.randn(100,5)

In [34]:
col_mean = F.mean(axis = 0)
col_std = F.std(axis = 0)

In [35]:
for i, (mean, std) in enumerate(zip(col_mean, col_std)):
    print(f"Feature {i+1}: mean = {mean:.4f}, std = {std:.4f}")

Feature 1: mean = 0.0256, std = 1.0430
Feature 2: mean = -0.1550, std = 0.8372
Feature 3: mean = 0.1553, std = 0.9681
Feature 4: mean = 0.0100, std = 1.0330
Feature 5: mean = 0.0601, std = 1.0335
