# Practice Day 5

##### NumPy ↔ Pandas Bridge & Scikit-learn Prep
##### to_numpy(), X/y pattern, StandardScaler manual, np.isnan()
##### Q1 Load titanic.csv into pandas. Extract the Age, Fare, and Survived columns as a NumPy array using .to_numpy(). Check its shape and dtype.
##### Q2 From that array, separate it into X (Age and Fare columns) and y (Survived column). Print their shapes — this is the exact format scikit-learn expects.
##### Q3 Using only NumPy on X, compute the mean and std of each column, then manually standardize X to have mean=0 and std=1. This is what StandardScaler does.
##### Q4 Using np.argmax() and np.argsort(), find the passenger with the highest Fare and list the top 5 passengers sorted by Age.
##### Q5 There are NaN values in Age. Use np.isnan() to find them, then replace them with the column mean — using only NumPy, no pandas.

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Q1 Load titanic.csv into pandas. Extract the Age, Fare, and Survived columns as a NumPy array using .to_numpy(). 
# Check its shape and dtype.

In [5]:
df = pd.read_csv(r'C:\Users\user\Desktop\Python1\DataSample\titanic.csv')
arr_1 = df[['Age','Fare','Survived']].to_numpy()
print(arr_1)
print(arr_1.shape)
print(arr_1.dtype)
print(arr_1.ndim)

[[22.      7.25    0.    ]
 [38.     71.2833  1.    ]
 [26.      7.925   1.    ]
 ...
 [    nan 23.45    0.    ]
 [26.     30.      1.    ]
 [32.      7.75    0.    ]]
(891, 3)
float64
2


In [ ]:
# Q2 From that array, separate it into X (Age and Fare columns) and y (Survived column). 
# Print their shapes — this is the exact format scikit-learn expects.

In [8]:
X = arr_1[:,0:2]
y = arr_1[:,-1]
print(X.shape)
print(y.shape)

(891, 2)
(891,)


In [ ]:
# Q3 Using only NumPy on X, compute the mean and std of each column, then manually standardize X to have mean=0 and std=1. This is what StandardScaler does.

In [34]:
col_mean = np.nanmean(X, axis=0)
col_std = np.nanstd(X, axis=0)
X_scaled = (X - col_mean) / col_std
print(X_scaled)
print(col_mean)
print(col_std)

[[-0.5924806  -0.50244517]
 [ 0.63878901  0.78684529]
 [-0.2846632  -0.48885426]
 ...
 [ 0.         -0.17626324]
 [-0.2846632  -0.04438104]
 [ 0.17706291 -0.49237783]]
[29.69911765 32.20420797]
[12.99471687 49.66553444]


In [ ]:
# Q4 Using np.argmax() and np.argsort(), find the passenger with the highest Fare and list the top 5 passengers sorted by Age.

In [23]:
print(X[np.argmax(X[:,1])])
X[np.argsort(X[:,0])[-5:]]


[ 35.     512.3292]


array([[     nan,   7.75  ],
       [     nan,   7.8292],
       [     nan,  13.8625],
       [     nan,   7.75  ],
       [     nan, 227.525 ]])

In [ ]:
# Q5 There are NaN values in Age. Use np.isnan() to find them, 
# then replace them with the column mean — using only NumPy, no pandas.

In [ ]:
np.isnan(X[:,0])
X[:,0][np.isnan(X[:,0])]=np.nanmean(X[:,0])

array([[22.        ,  7.25      ],
       [38.        , 71.2833    ],
       [26.        ,  7.925     ],
       ...,
       [29.69911765, 23.45      ],
       [26.        , 30.        ],
       [32.        ,  7.75      ]], shape=(891, 2))

In [32]:
np.isnan(X[:,0]).sum()

np.int64(0)

In [33]:
X[np.argsort(X[:,0])[-5:]]

array([[70.5   ,  7.75  ],
       [71.    , 34.6542],
       [71.    , 49.5042],
       [74.    ,  7.775 ],
       [80.    , 30.    ]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])