# Practice Day 3

##### Math, Aggregations & Broadcasting
##### ufuncs, axis parameter, broadcasting, np.where()
##### Q1 Create a 4×5 array of random integers (use np.random.randint()). Compute the sum, mean, and max along each axis. Explain what axis=0 vs axis=1 gives you.
##### Q2 Normalize a 1D array of 10 random numbers to the range [0, 1] using only NumPy operations. Formula: (x - x.min()) / (x.max() - x.min()).
##### Q3 Create a 3×3 array and add a 1D array [10, 20, 30] to it using broadcasting. Now try adding a column vector (reshape to (3,1)) and explain the difference.
##### Q4 Given array scores = np.array([45, 82, 91, 36, 78, 55, 88]), use np.where() to label each score as 'Pass' if >= 60, else 'Fail'.
##### Q5 Create a 5×5 array of random floats. Subtract the column mean from each column (hint: use axis=0 and broadcasting).

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Q1 Create a 4×5 array of random integers (use np.random.randint()). 
# Compute the sum, mean, and max along each axis. 
# Explain what axis=0 vs axis=1 gives you.

In [4]:
arr_q1 = np.random.randint(0,100,size=(4,5))
print(arr_q1)

[[78  4 64 28  5]
 [49 85  9  0 84]
 [ 7 84 71 91 71]
 [ 7 50  0 63 27]]


In [6]:
# Compute the sum, mean, and max along each axis. 
# axis = 0 -> result has shape of one row
print(np.sum(arr_q1,axis=0))
print(np.mean(arr_q1,axis=0))
print(np.max(arr_q1,axis=0))

[141 223 144 182 187]
[35.25 55.75 36.   45.5  46.75]
[78 85 71 91 84]


In [7]:
# axis = 1 -> result has shape of one col
print(np.sum(arr_q1,axis=1))
print(np.mean(arr_q1,axis=1))
print(np.max(arr_q1,axis=1))

[179 227 324 147]
[35.8 45.4 64.8 29.4]
[78 85 91 63]


In [ ]:
# Q2 Normalize a 1D array of 10 random numbers to the range [0, 1] using only NumPy operations. Formula: (x - x.min()) / (x.max() - x.min()).

In [19]:
arr_q2 = np.random.randint(1,100,10)
print(arr_q2)

[62 27  2  2 66 19 25 53 57 22]


In [20]:
(arr_q2 - arr_q2.min()) / (arr_q2.max() - arr_q2.min())

array([0.9375  , 0.390625, 0.      , 0.      , 1.      , 0.265625,
       0.359375, 0.796875, 0.859375, 0.3125  ])

In [ ]:
# Q3 Create a 3×3 array and add a 1D array [10, 20, 30] to it using broadcasting. 
# Now try adding a column vector (reshape to (3,1)) and explain the difference.

In [21]:
arr_q3 = np.random.randint(1,100,9).reshape(3,3)
print(arr_q3)

[[69  3 71]
 [ 7 15 14]
 [98 59 36]]


In [24]:
row = np.array([10, 20, 30])

In [26]:
arr_q3 + row # broadcast to each row

array([[ 79,  23, 101],
       [ 17,  35,  44],
       [108,  79,  66]])

In [33]:
col = row.reshape(3,1)
print(col)
print(col.shape)

[[10]
 [20]
 [30]]
(3, 1)


In [34]:
arr_q3 + col # broadcast to each col

array([[ 79,  13,  81],
       [ 27,  35,  34],
       [128,  89,  66]])

In [ ]:
# Q4 Given array scores = np.array([45, 82, 91, 36, 78, 55, 88]), 
# use np.where() to label each score as 'Pass' if >= 60, else 'Fail'.

In [35]:
scores = np.array([45, 82, 91, 36, 78, 55, 88])
np.where(scores >= 60, 'Pass', 'Fail')

array(['Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass'],
      dtype='<U4')

In [ ]:
# Q5 Create a 5×5 array of random floats. Subtract the column mean from each column (hint: use axis=0 and broadcasting).

In [40]:
arr_q5 = np.random.rand(5,5)
arr_q5

array([[0.02544374, 0.09919026, 0.74841348, 0.46026967, 0.99331611],
       [0.47419083, 0.29311169, 0.40047187, 0.47359212, 0.19740661],
       [0.93638987, 0.812207  , 0.72222029, 0.07905   , 0.95642684],
       [0.35881586, 0.45168982, 0.79068527, 0.16085163, 0.89811775],
       [0.17317229, 0.749086  , 0.04309983, 0.97346343, 0.66837344]])

In [ ]:
# Subtract the column mean from each column (hint: use axis=0 and broadcasting).

In [41]:
arr_q5 - np.mean(arr_q5,axis=0)

array([[-0.36815878, -0.38186669,  0.20743534,  0.0308243 ,  0.25058796],
       [ 0.08058831, -0.18794527, -0.14050628,  0.04414675, -0.54532154],
       [ 0.54278735,  0.33115004,  0.18124214, -0.35039537,  0.21369869],
       [-0.03478666, -0.02936714,  0.24970712, -0.26859374,  0.1553896 ],
       [-0.22043023,  0.26802905, -0.49787832,  0.54401806, -0.07435471]])

In [42]:
print((arr_q5 - np.mean(arr_q5, axis=0)).mean(axis=0))
# should be all ~0.0 — confirms each column is now mean-centered

[-2.22044605e-17  1.11022302e-17  0.00000000e+00 -2.22044605e-17
  0.00000000e+00]
